server:
  port: 1999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: users
#          uri: lb://users-service
#          predicates:
#          - Path=/users/**
#          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter:
#                  replenishRate: 500
#                  burstCapacity: 1000
#                  requestedTokens: 1
#        - id: comment
#          uri: lb://comment-service
#          predicates:
#          - Path=/comment/**
#        - id: product
#          uri: lb://product-service
#          predicates:
#          - Path=/product/**

#redis:
#  database: 0
#  host: localhost
#  port: 6379